import React from "react";

export default () => (
  <>
    <option value='Abkhazian'>Abkhazian</option>
    <option value='Aboriginal'>Aboriginal</option>
    <option value='Aché'>Aché</option>
    <option value='Acholi'>Acholi</option>
    <option value='Afrikaans'>Afrikaans</option>
    <option value='Aidoukrou'>Aidoukrou</option>
    <option value='Akan'>Akan</option>
    <option value='Albanian'>Albanian</option>
    <option value='Algonquin'>Algonquin</option>
    <option value='American Sign Language'>American Sign Language</option>
    <option value='Amharic'>Amharic</option>
    <option value='Apache languages'>Apache languages</option>
    <option value='Arabic'>Arabic</option>
    <option value='Aragonese'>Aragonese</option>
    <option value='Aramaic'>Aramaic</option>
    <option value='Arapaho'>Arapaho</option>
    <option value='Armenian'>Armenian</option>
    <option value='Assamese'>Assamese</option>
    <option value='Assyrian Neo-Aramaic'>Assyrian Neo-Aramaic</option>
    <option value='Athapascan languages'>Athapascan languages</option>
    <option value='Australian Sign Language'>Australian Sign Language</option>
    <option value='Awadhi'>Awadhi</option>
    <option value='Aymara'>Aymara</option>
    <option value='Azerbaijani'>Azerbaijani</option>
    <option value='Bable'>Bable</option>
    <option value='Baka'>Baka</option>
    <option value='Balinese'>Balinese</option>
    <option value='Bambara'>Bambara</option>
    <option value='Basque'>Basque</option>
    <option value='Bassari'>Bassari</option>
    <option value='Belarusian'>Belarusian</option>
    <option value='Bemba'>Bemba</option>
    <option value='Bengali'>Bengali</option>
    <option value='Berber languages'>Berber languages</option>
    <option value='Bhojpuri'>Bhojpuri</option>
    <option value='Bicolano'>Bicolano</option>
    <option value='Bodo'>Bodo</option>
    <option value='Bosnian'>Bosnian</option>
    <option value='Brazilian Sign Language'>Brazilian Sign Language</option>
    <option value='Breton'>Breton</option>
    <option value='British Sign Language'>British Sign Language</option>
    <option value='Bulgarian'>Bulgarian</option>
    <option value='Burmese'>Burmese</option>
    <option value='Cantonese'>Cantonese</option>
    <option value='Catalan'>Catalan</option>
    <option value='Central Khmer'>Central Khmer</option>
    <option value='Chaozhou'>Chaozhou</option>
    <option value='Chechen'>Chechen</option>
    <option value='Cherokee'>Cherokee</option>
    <option value='Cheyenne'>Cheyenne</option>
    <option value='Chhattisgarhi'>Chhattisgarhi</option>
    <option value='Chinese'>Chinese</option>
    <option value='Cornish'>Cornish</option>
    <option value='Corsican'>Corsican</option>
    <option value='Cree'>Cree</option>
    <option value='Creek'>Creek</option>
    <option value='Creole'>Creole</option>
    <option value='Creoles and pidgins'>Creoles and pidgins</option>
    <option value='Croatian'>Croatian</option>
    <option value='Crow'>Crow</option>
    <option value='Czech'>Czech</option>
    <option value='Danish'>Danish</option>
    <option value='Dari'>Dari</option>
    <option value='Desiya'>Desiya</option>
    <option value='Dinka'>Dinka</option>
    <option value='Djerma'>Djerma</option>
    <option value='Dogri'>Dogri</option>
    <option value='Dutch'>Dutch</option>
    <option value='Dyula'>Dyula</option>
    <option value='Dzongkha'>Dzongkha</option>
    <option value='East-Greenlandic'>East-Greenlandic</option>
    <option value='Eastern Frisian'>Eastern Frisian</option>
    <option value='Egyptian (Ancient)'>Egyptian (Ancient)</option>
    <option value='English'>English</option>
    <option value='Esperanto'>Esperanto</option>
    <option value='Estonian'>Estonian</option>
    <option value='Ewe'>Ewe</option>
    <option value='Faliasch'>Faliasch</option>
    <option value='Faroese'>Faroese</option>
    <option value='Filipino'>Filipino</option>
    <option value='Finnish'>Finnish</option>
    <option value='Flemish'>Flemish</option>
    <option value='Fon'>Fon</option>
    <option value='French'>French</option>
    <option value='French Sign Language'>French Sign Language</option>
    <option value='Fulah'>Fulah</option>
    <option value='Fur'>Fur</option>
    <option value='Gaelic'>Gaelic</option>
    <option value='Galician'>Galician</option>
    <option value='Georgian'>Georgian</option>
    <option value='German'>German</option>
    <option value='German Sign Language'>German Sign Language</option>
    <option value='Grebo'>Grebo</option>
    <option value='Greek'>Greek</option>
    <option value='Greek, Ancient (to 1453)'>Greek, Ancient (to 1453)</option>
    <option value='Greenlandic'>Greenlandic</option>
    <option value='Guarani'>Guarani</option>
    <option value='Gujarati'>Gujarati</option>
    <option value='Gumatj'>Gumatj</option>
    <option value='Gunwinggu'>Gunwinggu</option>
    <option value='Haitian'>Haitian</option>
    <option value='Haida'>Haida</option>
    <option value='Hakka'>Hakka</option>
    <option value='Haryanvi'>Haryanvi</option>
    <option value='Hassanya'>Hassanya</option>
    <option value='Hausa'>Hausa</option>
    <option value='Hawaiian'>Hawaiian</option>
    <option value='Hebrew'>Hebrew</option>
    <option value='Hindi'>Hindi</option>
    <option value='Hmong'>Hmong</option>
    <option value='Hokkien'>Hokkien</option>
    <option value='Hopi'>Hopi</option>
    <option value='Hungarian'>Hungarian</option>
    <option value='Iban'>Iban</option>
    <option value='Ibo'>Ibo</option>
    <option value='Icelandic'>Icelandic</option>
    <option value='Icelandic Sign Language'>Icelandic Sign Language</option>
    <option value='Indian Sign Language'>Indian Sign Language</option>
    <option value='Indonesian'>Indonesian</option>
    <option value='Inuktitut'>Inuktitut</option>
    <option value='Inupiaq'>Inupiaq</option>
    <option value='Irish Gaelic'>Irish Gaelic</option>
    <option value='Irula'>Irula</option>
    <option value='Italian'>Italian</option>
    <option value='Japanese'>Japanese</option>
    <option value='Japanese Sign Language'>Japanese Sign Language</option>
    <option value='Jola-Fonyi'>Jola-Fonyi</option>
    <option value="Ju'hoan">Ju'hoan</option>
    <option value='Kaado'>Kaado</option>
    <option value='Kabuverdianu'>Kabuverdianu</option>
    <option value='Kabyle'>Kabyle</option>
    <option value='Kalmyk-Oirat'>Kalmyk-Oirat</option>
    <option value='Kannada'>Kannada</option>
    <option value='Karajá'>Karajá</option>
    <option value='Karbi'>Karbi</option>
    <option value='Karen'>Karen</option>
    <option value='Kazakh'>Kazakh</option>
    <option value='Khanty'>Khanty</option>
    <option value='Khasi'>Khasi</option>
    <option value='Kikuyu'>Kikuyu</option>
    <option value='Kinyarwanda'>Kinyarwanda</option>
    <option value='Kirundi'>Kirundi</option>
    <option value='Klingon'>Klingon</option>
    <option value='Kodava'>Kodava</option>
    <option value='Konkani'>Konkani</option>
    <option value='Korean'>Korean</option>
    <option value='Korean Sign Language'>Korean Sign Language</option>
    <option value='Korowai'>Korowai</option>
    <option value='Kriolu'>Kriolu</option>
    <option value='Kru'>Kru</option>
    <option value='Kudmali'>Kudmali</option>
    <option value='Kuna'>Kuna</option>
    <option value='Kurdish'>Kurdish</option>
    <option value='Kwakiutl'>Kwakiutl</option>
    <option value='Kyrgyz'>Kyrgyz</option>
    <option value='Ladakhi'>Ladakhi</option>
    <option value='Ladino'>Ladino</option>
    <option value='Lao'>Lao</option>
    <option value='Latin'>Latin</option>
    <option value='Latvian'>Latvian</option>
    <option value='Limbu'>Limbu</option>
    <option value='Lingala'>Lingala</option>
    <option value='Lithuanian'>Lithuanian</option>
    <option value='Low German'>Low German</option>
    <option value='Luxembourgish'>Luxembourgish</option>
    <option value='Macedonian'>Macedonian</option>
    <option value='Macro-Jê'>Macro-Jê</option>
    <option value='Magahi'>Magahi</option>
    <option value='Maithili'>Maithili</option>
    <option value='Malagasy'>Malagasy</option>
    <option value='Malay'>Malay</option>
    <option value='Malayalam'>Malayalam</option>
    <option value='Malecite-Passamaquoddy'>Malecite-Passamaquoddy</option>
    <option value='Malinka'>Malinka</option>
    <option value='Maltese'>Maltese</option>
    <option value='Manchu'>Manchu</option>
    <option value='Mandarin'>Mandarin</option>
    <option value='Mandingo'>Mandingo</option>
    <option value='Manipuri'>Manipuri</option>
    <option value='Maori'>Maori</option>
    <option value='Mapudungun'>Mapudungun</option>
    <option value='Marathi'>Marathi</option>
    <option value='Marshallese'>Marshallese</option>
    <option value='Masai'>Masai</option>
    <option value='Masalit'>Masalit</option>
    <option value='Maya'>Maya</option>
    <option value='Mende'>Mende</option>
    <option value='Micmac'>Micmac</option>
    <option value='Middle English'>Middle English</option>
    <option value='Min Nan'>Min Nan</option>
    <option value='Minangkabau'>Minangkabau</option>
    <option value='Mirandese'>Mirandese</option>
    <option value='Mixtec'>Mixtec</option>
    <option value='Mizo'>Mizo</option>
    <option value='Mohawk'>Mohawk</option>
    <option value='Mongolian'>Mongolian</option>
    <option value='Montagnais'>Montagnais</option>
    <option value='More'>More</option>
    <option value='Morisyen'>Morisyen</option>
    <option value='Nagpuri'>Nagpuri</option>
    <option value='Nahuatl'>Nahuatl</option>
    <option value='Nama'>Nama</option>
    <option value='Navajo'>Navajo</option>
    <option value='Naxi'>Naxi</option>
    <option value='Ndebele'>Ndebele</option>
    <option value='Neapolitan'>Neapolitan</option>
    <option value='Nenets'>Nenets</option>
    <option value='Nepali'>Nepali</option>
    <option value="Nisga'a">Nisga'a</option>
    <option value='None'>None</option>
    <option value='Norse, Old'>Norse, Old</option>
    <option value='North American Indian'>North American Indian</option>
    <option value='Norwegian'>Norwegian</option>
    <option value='Nushi'>Nushi</option>
    <option value='Nyaneka'>Nyaneka</option>
    <option value='Nyanja'>Nyanja</option>
    <option value='Occitan'>Occitan</option>
    <option value='Ojibwa'>Ojibwa</option>
    <option value='Ojihimba'>Ojihimba</option>
    <option value='Old English'>Old English</option>
    <option value='Oriya'>Oriya</option>
    <option value='Papiamento'>Papiamento</option>
    <option value='Parsee'>Parsee</option>
    <option value='Pashtu'>Pashtu</option>
    <option value='Pawnee'>Pawnee</option>
    <option value='Persian'>Persian</option>
    <option value='Peul'>Peul</option>
    <option value='Polish'>Polish</option>
    <option value='Polynesian'>Polynesian</option>
    <option value='Portuguese'>Portuguese</option>
    <option value='Pular'>Pular</option>
    <option value='Punjabi'>Punjabi</option>
    <option value='Purepecha'>Purepecha</option>
    <option value='Quechua'>Quechua</option>
    <option value='Quenya'>Quenya</option>
    <option value='Rajasthani'>Rajasthani</option>
    <option value='Rawan'>Rawan</option>
    <option value='Romanian'>Romanian</option>
    <option value='Romansh'>Romansh</option>
    <option value='Romany'>Romany</option>
    <option value='Rotuman'>Rotuman</option>
    <option value='Russian'>Russian</option>
    <option value='Russian Sign Language'>Russian Sign Language</option>
    <option value='Ryukyuan'>Ryukyuan</option>
    <option value='Saami'>Saami</option>
    <option value='Samoan'>Samoan</option>
    <option value='Sanskrit'>Sanskrit</option>
    <option value='Sardinian'>Sardinian</option>
    <option value='Scanian'>Scanian</option>
    <option value='Serbian'>Serbian</option>
    <option value='Serbo-Croatian'>Serbo-Croatian</option>
    <option value='Serer'>Serer</option>
    <option value='Shanghainese'>Shanghainese</option>
    <option value='Shanxi'>Shanxi</option>
    <option value='Shona'>Shona</option>
    <option value='Shoshoni'>Shoshoni</option>
    <option value='Sicilian'>Sicilian</option>
    <option value='Sindarin'>Sindarin</option>
    <option value='Sindhi'>Sindhi</option>
    <option value='Sinhala'>Sinhala</option>
    <option value='Sioux'>Sioux</option>
    <option value='Slovak'>Slovak</option>
    <option value='Slovenian'>Slovenian</option>
    <option value='Somali'>Somali</option>
    <option value='Songhay'>Songhay</option>
    <option value='Soninke'>Soninke</option>
    <option value='Sorbian languages'>Sorbian languages</option>
    <option value='Sotho'>Sotho</option>
    <option value='Sousson'>Sousson</option>
    <option value='Spanish'>Spanish</option>
    <option value='Spanish Sign Language'>Spanish Sign Language</option>
    <option value='Sranan'>Sranan</option>
    <option value='Swahili'>Swahili</option>
    <option value='Swedish'>Swedish</option>
    <option value='Swiss German'>Swiss German</option>
    <option value='Sylheti'>Sylheti</option>
    <option value='Tagalog'>Tagalog</option>
    <option value='Tajik'>Tajik</option>
    <option value='Tamashek'>Tamashek</option>
    <option value='Tamil'>Tamil</option>
    <option value='Tarahumara'>Tarahumara</option>
    <option value='Tatar'>Tatar</option>
    <option value='Telugu'>Telugu</option>
    <option value='Teochew'>Teochew</option>
    <option value='Thai'>Thai</option>
    <option value='Tibetan'>Tibetan</option>
    <option value='Tigrigna'>Tigrigna</option>
    <option value='Tlingit'>Tlingit</option>
    <option value='Tok Pisin'>Tok Pisin</option>
    <option value='Tonga (Tonga Islands)'>Tonga (Tonga Islands)</option>
    <option value='Tsonga'>Tsonga</option>
    <option value='Tswa'>Tswa</option>
    <option value='Tswana'>Tswana</option>
    <option value='Tulu'>Tulu</option>
    <option value='Tupi'>Tupi</option>
    <option value='Turkish'>Turkish</option>
    <option value='Turkmen'>Turkmen</option>
    <option value='Tuvinian'>Tuvinian</option>
    <option value='Tzotzil'>Tzotzil</option>
    <option value='Ukrainian'>Ukrainian</option>
    <option value='Ukrainian Sign Language'>Ukrainian Sign Language</option>
    <option value='Ungwatsi'>Ungwatsi</option>
    <option value='Urdu'>Urdu</option>
    <option value='Uzbek'>Uzbek</option>
    <option value='Vietnamese'>Vietnamese</option>
    <option value='Visayan'>Visayan</option>
    <option value='Washoe'>Washoe</option>
    <option value='Welsh'>Welsh</option>
    <option value='Wolof'>Wolof</option>
    <option value='Xhosa'>Xhosa</option>
    <option value='Yakut'>Yakut</option>
    <option value='Yapese'>Yapese</option>
    <option value='Yiddish'>Yiddish</option>
    <option value='Yoruba'>Yoruba</option>
    <option value='Zulu'>Zulu</option>
  </>
);
